/**
 * node-sdk e2e: Phase D2 — v1-authored session history must load in the v2 engine.
 *
 * Historical-data compatibility: sessions persisted by the legacy engine
 * (`@mirri-ai/agent-core`, "v1") live under `<MIRRICODE_HOME>/sessions/<wd>/<id>/`
 * as `state.json` + `agents/<agent>/wire.jsonl`. The v2 engine
 * (`@mirri-ai/agent-core-v2`) reads the same directory layout and migrates the
 * shared wire protocol (1.x). This suite proves that real v1-produced sessions —
 * not hand-invented fixtures — survive the crossover:
 *
 *   Given  a session generated by a real v1 engine fixture (fake provider)
 *   When   the v2 engine boots on the same MIRRICODE_HOME and resumes it
 *   Then   resume succeeds, session metadata/history carry over, the wire
 *          journal is untouched, and a brand-new turn can be appended.
 *
 * Three historical shapes are covered, standing in for distinct v1 feature
 * history (the D2 requirement of "at least 3 previous-major-version session
 * records"):
 *
 *   A. plain-text session        — `turn.prompt` / `context.append_message`
 *   B. tool-calling session      — `context.append_loop_event` tool.call /
 *                                  tool.result + Bash tool execution
 *   C. compacted session         — `full_compaction.begin` /
 *                                  `context.apply_compaction` + summary
 *
 * All LLM traffic goes to a fake OpenAI-compatible provider — no real model.
 */

import { readFile, readdir } from 'node:fs/promises';
import { join } from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import {
  type EngineFixture,
  type FakeProviderServer,
  createEngineFixture,
  createFakeProviderServer,
  makeTempDir,
  removeTempDir,
} from '@mirri-ai/e2e-harness';

import type { Session } from '#/index';

// ---------------------------------------------------------------------------
// Shared teardown
// ---------------------------------------------------------------------------

const tempDirs: string[] = [];
const openFixtures: EngineFixture[] = [];
const openFakeProviders: FakeProviderServer[] = [];

afterEach(async () => {
  for (const fake of openFakeProviders.splice(0)) {
    try {
      await fake.close();
    } catch {
      // best-effort teardown
    }
  }
  for (const fixture of openFixtures.splice(0)) {
    try {
      await fixture.close();
    } catch {
      // best-effort teardown
    }
  }
  for (const dir of tempDirs.splice(0)) {
    await removeTempDir(dir);
  }
});

function trackFixture(fixture: EngineFixture): EngineFixture {
  openFixtures.push(fixture);
  return fixture;
}

function trackFakeProvider(fake: FakeProviderServer): FakeProviderServer {
  openFakeProviders.push(fake);
  return fake;
}

// ---------------------------------------------------------------------------
// Record/disk helpers
// ---------------------------------------------------------------------------

async function newFixture(
  fakeProvider: FakeProviderServer,
  homeDir: string,
  engine: 'v1' | 'v2',
): Promise<EngineFixture> {
  return trackFixture(await createEngineFixture({ fakeProvider, homeDir }, engine));
}

/** Resolve `<MIRRICODE_HOME>/sessions/<workdir-bucket>/<sessionId>` by scanning buckets. */
async function resolveSessionDir(homeDir: string, sessionId: string): Promise<string> {
  const buckets = await readdir(join(homeDir, 'sessions'), { withFileTypes: true });
  for (const bucket of buckets) {
    if (!bucket.isDirectory()) continue;
    const candidate = join(homeDir, 'sessions', bucket.name, sessionId);
    try {
      await readdir(candidate);
      return candidate;
    } catch {
      // not this bucket
    }
  }
  throw new Error(`v1 session dir not found under ${homeDir}/sessions for id ${sessionId}`);
}

interface ParsedV1Session {
  readonly sessionId: string;
  readonly sessionDir: string;
  readonly state: Record<string, unknown>;
  readonly wire: ReadonlyArray<Record<string, unknown>>;
}

async function readV1Session(homeDir: string, sessionId: string): Promise<ParsedV1Session> {
  const sessionDir = await resolveSessionDir(homeDir, sessionId);
  const state = JSON.parse(
    await readFile(join(sessionDir, 'state.json'), 'utf8'),
  ) as Record<string, unknown>;
  const rawWire = await readFile(join(sessionDir, 'agents', 'main', 'wire.jsonl'), 'utf8');
  const wire = rawWire
    .split('\n')
    .filter((line) => line.trim().length > 0)
    .map((line) => JSON.parse(line) as Record<string, unknown>);
  return { sessionId, sessionDir, state, wire };
}

function wireHas(wire: ReadonlyArray<Record<string, unknown>>, type: string): boolean {
  return wire.some((record) => record['type'] === type);
}

function loopEventOfType(
  wire: ReadonlyArray<Record<string, unknown>>,
  eventType: string,
): Record<string, unknown> | undefined {
  return wire
    .filter((record) => record['type'] === 'context.append_loop_event')
    .map((record) => record['event'] as Record<string, unknown>)
    .find((event) => event['type'] === eventType);
}

/** Drive a raw SDK Session through one full turn, waiting for `turn.ended`. */
async function promptRawSession(
  session: Session,
  input: string,
  timeoutMs = 15_000,
): Promise<void> {
  const turnEnded = new Promise<void>((resolve, reject) => {
    const timer = setTimeout(
      () => reject(new Error(`timed out waiting for turn.ended after "${input}"`)),
      timeoutMs,
    );
    const unsubscribe = session.onEvent((event) => {
      if (event.type === 'turn.ended') {
        clearTimeout(timer);
        unsubscribe();
        resolve();
      }
    });
  });
  await session.prompt(input);
  await turnEnded;
}

/** Queue several identical fake-text responses so extra stream steps never starve. */
function queueTexts(fake: FakeProviderServer, text: string, count = 3): void {
  for (let index = 0; index < count; index += 1) fake.nextText(text);
}

// ---------------------------------------------------------------------------
// Shape generators — real v1 engine, fake provider (the Given phase)
// ---------------------------------------------------------------------------

/** Shape A: a plain text conversation, two turns. */
async function givenPlainTextV1Session(homeDir: string, workDir: string): Promise<ParsedV1Session> {
  const fake = trackFakeProvider(await createFakeProviderServer());
  const fixture = await newFixture(fake, homeDir, 'v1');

  const session = await fixture.createSession({ id: 'v1-history-text-session', workDir });
  fake.nextText('Paris is the capital of France.');
  await session.prompt('What is the capital of France?');
  await session.waitForTurnEnd();

  fake.nextText('About 2.1 million people live in the city.');
  await session.prompt('What about its population?');
  await session.waitForTurnEnd();

  await session.close();
  await fixture.close();
  await fake.close();
  return readV1Session(homeDir, session.id);
}

/** Shape B: a tool-calling session — the main agent runs one `Bash` tool call. */
async function givenToolCallingV1Session(homeDir: string, workDir: string): Promise<ParsedV1Session> {
  const fake = trackFakeProvider(await createFakeProviderServer());
  const fixture = await newFixture(fake, homeDir, 'v1');

  const session = await fixture.createSession({
    id: 'v1-history-tool-session',
    workDir,
    permission: 'auto',
  });
  fake.nextText('The system looks healthy.');
  await session.prompt('Check system health');
  await session.waitForTurnEnd();

  fake.nextToolCall('Bash', { command: 'echo v1-tool-call-042' });
  fake.nextText('The verification command finished successfully.');
  await session.prompt('Run the verification command');
  await session.waitForTurnEnd();

  await session.close();
  await fixture.close();
  await fake.close();
  return readV1Session(homeDir, session.id);
}

/** Shape C: a session that survived a manual full compaction. */
async function givenCompactedV1Session(homeDir: string, workDir: string): Promise<ParsedV1Session> {
  const fake = trackFakeProvider(await createFakeProviderServer());
  const fixture = await newFixture(fake, homeDir, 'v1');

  const session = await fixture.rawHarness.createSession({
    id: 'v1-history-compact-session',
    workDir,
  });

  fake.nextText('The planets orbit the Sun in order of distance.');
  await promptRawSession(session, 'First task: list the planets in order.');

  fake.nextText('Jupiter is the largest planet.');
  await promptRawSession(session, 'Second task: which planet is the largest?');

  // Manual full compaction: one summarizer LLM call, then `full_compaction.begin`
  // + `context.apply_compaction` records are persisted to the journal.
  fake.nextText('PLANET-SUMMARY: user asked about planets; assistant listed them and named Jupiter the largest.');
  await session.compact({ instruction: 'Keep the essential conversation facts.' });

  fake.nextText('The ringed planet is Saturn.');
  await promptRawSession(session, 'Third task: which planet has rings?');

  await session.close();
  await fixture.close();
  await fake.close();
  return readV1Session(homeDir, session.id);
}

// ---------------------------------------------------------------------------
// v2 phase shared assertions (the When/Then phases)
// ---------------------------------------------------------------------------

interface ResumeThenAssertions {
  readonly newTurnQuestion: string;
  /** Assert these literal fragments appear inside the v2 LLM `messages` body. */
  readonly inheritedFragments: readonly string[];
}

/**
 * Boot v2 on the same homeDir, resume the v1 session, and verify the full
 * compat contract: metadata carry-over, wire journal untouched, and the
 * ability to start a new turn whose model request still sees history.
 */
async function whenV2ResumesThenContinues(
  homeDir: string,
  parsed: ParsedV1Session,
  expected: ResumeThenAssertions,
): Promise<void> {
  const v2Fake = trackFakeProvider(await createFakeProviderServer());
  const v2 = await newFixture(v2Fake, homeDir, 'v2');

  const wirePath = join(parsed.sessionDir, 'agents', 'main', 'wire.jsonl');
  const wireBefore = await readFile(wirePath, 'utf8');

  // When: v2 resumes the v1 session through the same MirriHarness surface the
  // fixture wrapper exposes.
  const resumed: Session = await v2.rawHarness.resumeSession({ id: parsed.sessionId });
  expect(resumed.id).toBe(parsed.sessionId);

  // Then: metadata survived.
  const resumeState = resumed.getResumeState();
  expect(resumeState).toBeDefined();
  const sessionMetadata = resumeState!.sessionMetadata;
  expect(sessionMetadata.lastPrompt).toBe(parsed.state['lastPrompt']);
  expect(Date.parse(sessionMetadata.createdAt)).toBe(Date.parse(String(parsed.state['createdAt'])));
  expect(sessionMetadata.title).toBe(parsed.state['title'] ?? 'New Session');
  expect(sessionMetadata.custom).toEqual(parsed.state['custom'] ?? {});
  expect(resumed.workDir).toBe(parsed.state['workDir']);

  // Then: the journal was not rewritten by the migration layer (already 1.5).
  const wireAfterResume = await readFile(wirePath, 'utf8');
  expect(wireAfterResume).toBe(wireBefore);

  // Then: a brand-new turn works and carries the v1 history into the model
  // request together with the new user input.
  queueTexts(v2Fake, 'v2 continuation response');
  await promptRawSession(resumed, expected.newTurnQuestion);

  const requestCountBeforePrompt = v2Fake.requests.length;
  expect(requestCountBeforePrompt).toBeGreaterThan(0);
  const lastBody = v2Fake.requests[requestCountBeforePrompt - 1]!.bodyJson as {
    messages?: readonly unknown[];
  };
  const messagesJson = JSON.stringify(lastBody?.messages ?? []);
  for (const fragment of expected.inheritedFragments) {
    expect(messagesJson).toContain(fragment);
  }
  expect(messagesJson).toContain(expected.newTurnQuestion);

  await resumed.close();
  await v2.close();
}

// ---------------------------------------------------------------------------
// Scenarios — Given-When-Then
// ---------------------------------------------------------------------------

describe('node-sdk e2e: v1 session history loads in the v2 engine (Phase D2)', () => {
  it('Given a v1 plain-text session, When v2 resumes it, Then metadata and history are preserved and a new turn continues', async () => {
    const homeDir = await makeTempDir();
    const workDir = await makeTempDir();
    tempDirs.push(homeDir, workDir);

    const session = await givenPlainTextV1Session(homeDir, workDir);

    // Given-proof: real v1 journal with the expected record vocabulary.
    expect(session.wire[0]).toMatchObject({ type: 'metadata', protocol_version: '1.5' });
    expect(wireHas(session.wire, 'turn.prompt')).toBe(true);
    expect(wireHas(session.wire, 'context.append_message')).toBe(true);
    expect(session.state['version']).toBeUndefined(); // v1 metadata layout
    expect(session.state['lastPrompt']).toBe('What about its population?');

    await whenV2ResumesThenContinues(homeDir, session, {
      newTurnQuestion: 'v2 continuation: what about the Eiffel Tower?',
      inheritedFragments: [
        'What is the capital of France?', // first v1 user message
        'Paris is the capital of France.', // first v1 assistant answer
      ],
    });
  });

  it('Given a v1 session with tool call + result history, When v2 resumes it, Then the tool history is preserved and a new turn continues', async () => {
    const homeDir = await makeTempDir();
    const workDir = await makeTempDir();
    tempDirs.push(homeDir, workDir);

    const session = await givenToolCallingV1Session(homeDir, workDir);

    // Given-proof: the journal really records tool.call / tool.result loop events.
    const toolCall = loopEventOfType(session.wire, 'tool.call');
    expect(toolCall).toBeDefined();
    expect(toolCall!['name']).toBe('Bash');
    const toolResult = loopEventOfType(session.wire, 'tool.result');
    expect(toolResult).toBeDefined();
    expect(session.state['lastPrompt']).toBe('Run the verification command');

    await whenV2ResumesThenContinues(homeDir, session, {
      newTurnQuestion: 'v2 continuation: summarize the verification result.',
      inheritedFragments: [
        'Run the verification command', // the tool-calling v1 user prompt
        'v1-tool-call-042', // echoed command output inside the tool result
      ],
    });
  });

  it('Given a v1 session with a full compaction, When v2 resumes it, Then the compacted summary is preserved and a new turn continues', async () => {
    const homeDir = await makeTempDir();
    const workDir = await makeTempDir();
    tempDirs.push(homeDir, workDir);

    const session = await givenCompactedV1Session(homeDir, workDir);

    // Given-proof: the compaction record pair is in the v1 journal.
    expect(wireHas(session.wire, 'full_compaction.begin')).toBe(true);
    expect(
      session.wire.find((record) => record['type'] === 'full_compaction.begin'),
    ).toMatchObject({ source: 'manual', instruction: 'Keep the essential conversation facts.' });
    expect(wireHas(session.wire, 'context.apply_compaction')).toBe(true);
    expect(session.state['lastPrompt']).toBe('Third task: which planet has rings?');

    await whenV2ResumesThenContinues(homeDir, session, {
      newTurnQuestion: 'v2 continuation: recap the compacted conversation.',
      inheritedFragments: ['PLANET-SUMMARY', 'Jupiter', 'Saturn'],
    });
  });
});